function createfigure(YMatrix1, X1, Y1, X2)
%CREATEFIGURE(YMATRIX1,X1,Y1,X2)
%  YMATRIX1:  matrix of y data
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data

%  Auto-generated by MATLAB on 05-Feb-2013 09:13:42

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[255215.852661692 283286.734510475]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[3042.06042505006 4780.13267840097]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','sweep');
set(plot1(2),'DisplayName','v.sync');

% Create plot
plot(X1,Y1,'Parent',axes1,'Marker','x','LineStyle','none','Color',[0 1 0],...
    'DisplayName','sweep tick');

% Create plot
plot(X2,Y1,'Parent',axes1,'Marker','diamond','LineStyle','none',...
    'Color',[1 0 0],...
    'DisplayName','v.sync tick');

% Create xlabel
xlabel({'sample @ 20kHz'});

% Create ylabel
ylabel({'arbitrary voltage'});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.846553851577649 0.717857142857143 0.0634584875727128 0.188888888888889]);

